src/Entity/ConteinerMovimentacoes.php
<?php

namespace App\Entity;

use App\Repository\ConteinerMovimentacoesRepository;
use App\Repository\ConteinerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ConteinerMovimentacoesRepository::class)
 */
class ConteinerMovimentacoes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $movement_type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dt_inicio;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dt_fim;

    /**
     * @ORM\ManyToMany(targetEntity=Conteiner::class, inversedBy="cont_movimenta")
     */
    private $container_number;

    public function __construct()
    {
        $this->container_number = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMovementType(): ?string
    {
        return $this->movement_type;
    }

    public function setMovementType(string $movement_type): self
    {
        $this->movement_type = $movement_type;

        return $this;
    }

    public function getDtInicio(): ?\DateTimeInterface
    {
        return $this->dt_inicio;
    }

    public function setDtInicio(\DateTimeInterface $dt_inicio): self
    {
        $this->dt_inicio = $dt_inicio;

        return $this;
    }

    public function getDtFim(): ?\DateTimeInterface
    {
        return $this->dt_fim;
    }

    public function setDtFim(\DateTimeInterface $dt_fim): self
    {
        $this->dt_fim = $dt_fim;

        return $this;
    }

    /**
     * @return Collection|Conteiner[]
     */
    public function getContainerNumber(): Collection
    {
        return $this->container_number;
    }

    public function addContainerNumber(Conteiner $containerNumber): self
    {
        if (!$this->container_number->contains($containerNumber)) {
            $this->container_number[] = $containerNumber;
        }

        return $this;
    }

    public function removeContainerNumber(Conteiner $containerNumber): self
    {
        $this->container_number->removeElement($containerNumber);

        return $this;
    }

    public function __toString()
    {
        // to show the name of the Category in the select
        return $this->movement_type;
        // to show the id of the Category in the select
        // return $this->id;
    }
}

src/Form/ConteinerMovimentacoesType.php
<?php

namespace App\Form;

use App\Entity\ConteinerMovimentacoes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConteinerMovimentacoesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('movement_type')
            ->add('dt_inicio')
            ->add('dt_fim')
            ->add('container_number')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ConteinerMovimentacoes::class,
        ]);
    }
}

src/Controller/ConteinerMovimentacoesController.php
<?php

namespace App\Controller;

use App\Entity\ConteinerMovimentacoes;
use App\Form\ConteinerMovimentacoesType;
use App\Repository\ConteinerMovimentacoesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/movimentacoes')]
class ConteinerMovimentacoesController extends AbstractController
{
    #[Route('/', name: 'conteiner_movimentacoes_index', methods: ['GET'])]
    public function index(ConteinerMovimentacoesRepository $conteinerMovimentacoesRepository): Response
    {
        return $this->render('conteiner_movimentacoes/index.html.twig', [
            'conteiner_movimentacoes' => $conteinerMovimentacoesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'conteiner_movimentacoes_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $conteinerMovimentaco = new ConteinerMovimentacoes();
        $form = $this->createForm(ConteinerMovimentacoesType::class, $conteinerMovimentaco);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($conteinerMovimentaco);
            $entityManager->flush();

            return $this->redirectToRoute('conteiner_movimentacoes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('conteiner_movimentacoes/new.html.twig', [
            'conteiner_movimentaco' => $conteinerMovimentaco,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'conteiner_movimentacoes_show', methods: ['GET'])]
    public function show(ConteinerMovimentacoes $conteinerMovimentaco): Response
    {
        return $this->render('conteiner_movimentacoes/show.html.twig', [
            'conteiner_movimentaco' => $conteinerMovimentaco,
        ]);
    }

    #[Route('/{id}/edit', name: 'conteiner_movimentacoes_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, ConteinerMovimentacoes $conteinerMovimentaco, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ConteinerMovimentacoesType::class, $conteinerMovimentaco);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('conteiner_movimentacoes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('conteiner_movimentacoes/edit.html.twig', [
            'conteiner_movimentaco' => $conteinerMovimentaco,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'conteiner_movimentacoes_delete', methods: ['POST'])]
    public function delete(Request $request, ConteinerMovimentacoes $conteinerMovimentaco, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$conteinerMovimentaco->getId(), $request->request->get('_token'))) {
            $entityManager->remove($conteinerMovimentaco);
            $entityManager->flush();
        }

        return $this->redirectToRoute('conteiner_movimentacoes_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/conteiner_movimentacoes/_delete_form.html.twig
<form method="post" action="{{ path('conteiner_movimentacoes_delete', {'id': conteiner_movimentaco.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ conteiner_movimentaco.id) }}">
    <button class="btn">Delete</button>
</form>

templates/conteiner_movimentacoes/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/conteiner_movimentacoes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit ConteinerMovimentacoes{% endblock %}

{% block body %}
    <h1>Edit ConteinerMovimentacoes</h1>

    {{ include('conteiner_movimentacoes/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('conteiner_movimentacoes_index') }}">back to list</a>

    {{ include('conteiner_movimentacoes/_delete_form.html.twig') }}
{% endblock %}

templates/conteiner_movimentacoes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}ConteinerMovimentacoes index{% endblock %}

{% block body %}
    <h1>ConteinerMovimentacoes index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Movimentações</th>
                <th>Dt_inicio</th>
                <th>Dt_fim</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for conteiner_movimentaco in conteiner_movimentacoes %}
            <tr>
                <td>{{ conteiner_movimentaco.id }}</td>
                <td>{{ conteiner_movimentaco.movementType }}</td>
                <td>{{ conteiner_movimentaco.dtInicio ? conteiner_movimentaco.dtInicio|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ conteiner_movimentaco.dtFim ? conteiner_movimentaco.dtFim|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('conteiner_movimentacoes_show', {'id': conteiner_movimentaco.id}) }}">show</a>
                    <a href="{{ path('conteiner_movimentacoes_edit', {'id': conteiner_movimentaco.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('conteiner_movimentacoes_new') }}">Create new</a>
{% endblock %}

templates/conteiner_movimentacoes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New ConteinerMovimentacoes{% endblock %}

{% block body %}
    <h1>Create new ConteinerMovimentacoes</h1>

    {{ include('conteiner_movimentacoes/_form.html.twig') }}

    <a href="{{ path('conteiner_movimentacoes_index') }}">back to list</a>
{% endblock %}

templates/conteiner_movimentacoes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}ConteinerMovimentacoes{% endblock %}

{% block body %}
    <h1>ConteinerMovimentacoes</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ conteiner_movimentaco.id }}</td>
            </tr>
            <tr>
                <th>Movement_type</th>
                <td>{{ conteiner_movimentaco.movementType }}</td>
            </tr>
            <tr>
                <th>Dt_inicio</th>
                <td>{{ conteiner_movimentaco.dtInicio ? conteiner_movimentaco.dtInicio|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Dt_fim</th>
                <td>{{ conteiner_movimentaco.dtFim ? conteiner_movimentaco.dtFim|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('conteiner_movimentacoes_index') }}">back to list</a>

    <a href="{{ path('conteiner_movimentacoes_edit', {'id': conteiner_movimentaco.id}) }}">edit</a>

    {{ include('conteiner_movimentacoes/_delete_form.html.twig') }}
{% endblock %}